# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreBanking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='CustomerAccount',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_ship_type',
            new_name='membership_type',
        ),
    ]
