# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreBanking', '0002_auto_20170130_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='center',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
