# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreBanking', '0003_auto_20170130_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='name',
        ),
        migrations.AddField(
            model_name='center',
            name='center_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
