# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreBanking', '0004_auto_20170130_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='city',
            new_name='name',
        ),
    ]
